---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - cluster_manager
  debug:
    msg: "role '{{ role_name }}' start"

- name: apply baseconfig app org_cluster_manager_base
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_cluster_manager_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_manager_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: site is not defined

- name: apply baseconfig app org_multisite_manager_base
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_multisite_manager_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_multisite_manager_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: site is defined

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and inventory_hostname not in groups.role_indexer

- name: install certs for web ssl
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_all_search_base
    - web_ssl
  include_role:
    name: baseconfig_app
    tasks_from: splunk_ssl_web_certs
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and splunk_license_manager|default()|length > 0 and inventory_hostname not in groups.role_license_manager|default([])

- name: apply baseconfig app org_indexer_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_indexer_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_indexer_volume_indexes'
    app_path: '{{splunk_home}}/etc/{{splunk_cluster_manager_apps}}'

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/{{splunk_cluster_manager_apps}}'

- name: apply baseconfig app org_s2_indexer_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_s2_indexer_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_s2_indexer_indexes'
    app_path: '{{splunk_home}}/etc/{{splunk_cluster_manager_apps}}'
  when: splunk_volume_defaults.remotePath is defined

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - cluster_manager
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/{{splunk_cluster_manager_apps}}'
  when: splunk_license_manager|default()|length > 0

- name: call update_dserver from role monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
  vars:
    splunk_dservers: "[ '{{ inventory_hostname }}' ]"
  when: splunk_monitoring_console|default()|length > 0 and inventory_hostname not in groups.role_monitoring_console
