---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - deployer
  debug:
    msg: "role '{{ role_name }}' start"

- name: "check if shclustering pass4SymmKey exists"
  tags:
    - splunk
    - deployer
  shell: "{{ splunk_home }}/bin/splunk btool server list shclustering | egrep -we '^pass4SymmKey'"
  become: yes
  become_user: "{{ splunk_user }}"
  register: grep_result
  check_mode: no
  failed_when: "grep_result.rc > 1"
  changed_when: "grep_result.rc == 1"

- name: "setting pass4SymmKey"
  tags:
    - splunk
    - deployer
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: pass4SymmKey
    value: "{{splunk_shc_pass}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: "grep_result.rc == 1"

- name: "setting shclustering label"
  tags:
    - splunk
    - deployer
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: shcluster_label
    value: "{{splunk_shc_label}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and inventory_hostname not in groups.role_indexer

- name: install certs for web ssl
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_search_base
    - web_ssl
  include_role:
    name: baseconfig_app
    tasks_from: splunk_ssl_web_certs
  when: splunk_ssl.web.enable == true and splunk_ssl.web.own_certs == true

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and splunk_license_manager|default()|length > 0 and inventory_hostname not in groups.role_license_manager|default([])

- name: apply baseconfig app org_search_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_search_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_search_volume_indexes'
    app_path: '{{splunk_home}}/etc/shcluster/apps'

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/shcluster/apps'

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/shcluster/apps'

- name: apply baseconfig app org_cluster_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{ splunk_home }}/etc/shcluster/apps'
    splunk_search_peer_list: "{{ hostvars[groups['search_peer_'+splunk_env_name+'_'+search_peer_name][0]]['splunk_search_peer_list'] }}"
  with_items: "{{ splunk_search_peer_name_list }}"
  loop_control:
    loop_var: search_peer_name
  when: splunk_idxc_cm_list|length > 0

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/shcluster/apps'
    splunk_output_list: "{{ hostvars[groups['output_'+splunk_env_name+'_'+output_name][0]]['splunk_output_list'] }}"
  with_items: "{{ splunk_outputs_name_list }}"
  loop_control:
    loop_var: output_name

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - deployer
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/shcluster/apps'
  when: splunk_license_manager|default()|length > 0

- name: call update_dserver from role monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
  vars:
    splunk_dservers: "[ '{{ inventory_hostname }}' ]"
  when: splunk_monitoring_console|default()|length > 0 and inventory_hostname not in groups.role_monitoring_console
