---
# This playbook configures an LDAP server

# Following this guide: http://www.itzgeek.com/how-tos/linux/centos-how-tos/step-step-openldap-server-configuration-centos-7-rhel-7.html

- name: install openladp packages
  tags:
    - ldap
  package:
    name:
      - openldap
      - openldap-clients
      - openldap-servers
    state: latest

- name: enable and start service slapd
  tags:
    - ldap
  service: 
    name: slapd
    state: started
    enabled: yes

- name: check for ldap db config file
  tags:
    - ldap
  stat: path="/var/tmp/db.ldif"
  register: ldap_config

- name: create LDAP root password
  tags:
    - ldap
  shell: slappasswd -s {{ldap_root_passwd}}
  register: ldap_root_hash
  when: ldap_config.stat.exists == false

- name: define ldap db config file
  tags:
    - ldap
  template:
    src: var/tmp/db.ldif.j2
    dest: /var/tmp/db.ldif
  when: ldap_config.stat.exists == false

- name: add ldap db config file
  tags:
    - ldap
  shell: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /var/tmp/db.ldif
  when: ldap_config.stat.exists == false

- name: "check for ldap monitor config file"
  stat: path="/var/tmp/monitor.ldif"
  register: ldap_monitor_config

- name: define monitor config file
  tags:
    - ldap
  template:
    src: var/tmp/monitor.ldif.j2
    dest: /var/tmp/monitor.ldif
  when: ldap_monitor_config.stat.exists == false

- name: add ldap monitor config
  tags:
    - ldap
  shell: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /var/tmp/monitor.ldif
  when: ldap_monitor_config.stat.exists == false

- name: check for ldap DB_CONFIG file
  tags:
    - ldap
  stat: path="/var/lib/ldap/DB_CONFIG"
  register: ldap_db_config

- name: copy /var/lib/ldap/DB_CONFIG from example
  tags:
    - ldap
  shell: cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
  when: ldap_db_config.stat.exists == false

- name: set correct file permissions for DB_CONFIG
  tags:
    - ldap
  file:
    path: /var/lib/ldap/DB_CONFIG
    owner: ldap
    group: ldap
    mode: 0644

- name: add more schemas
  tags:
    - ldap
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{item}}
  with_items:
    - /etc/openldap/schema/cosine.ldif
    - /etc/openldap/schema/nis.ldif
    - /etc/openldap/schema/inetorgperson.ldif
  when: ldap_db_config.stat.exists == false

- name: "check for ldap base config file"
  tags:
    - ldap
  stat: path="/var/tmp/base.ldif"
  register: ldap_base_config

- name: define domain config
  tags:
    - ldap
  template:
    src: var/tmp/base.ldif.j2
    dest: /var/tmp/base.ldif
  when: ldap_base_config.stat.exists == false

- name: build lDAP directory sturcture
  tags:
    - ldap
  shell: ldapadd -x -w {{ldap_root_passwd}} -D "cn=ldapadm,{{ldap_dc}}" -f /var/tmp/base.ldif
  when: ldap_base_config.stat.exists == false
