---
# This playbook contains common tasks in this role

- name: start search single head
  tags:
    - splunk
    - search_head
    - shsingle
  debug:
    msg: "Configuring single search head"

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_all_forwarder_outputs
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_forwarder_outputs'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and inventory_hostname not in groups.role_indexer

- name: apply baseconfig app org_all_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and splunk_license_manager|default()|length > 0 and inventory_hostname not in groups.role_license_manager|default([])

- name: apply baseconfig app org_search_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_search_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_search_volume_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and inventory_hostname not in groups.role_indexer

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and inventory_hostname not in groups.role_indexer

- name: apply baseconfig app org_cluster_search_base
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
    - org_cluster_search_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_search_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and splunk_search_peer_idxc_list|length > 0 and inventory_hostname not in groups.role_cluster_manager

- name: add indexer as search pears
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - shsingle
  include_tasks: search_peers.yml
  when: inventory_hostname not in groups.role_indexer

- name: call update_dserver from role monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
  vars:
    splunk_dservers: "[ '{{ inventory_hostname }}' ]"
  when: splunk_monitoring_console|default()|length > 0 and inventory_hostname not in groups.role_monitoring_console

- name: set global permissions for comment macro
  include_tasks: comment_macro.yml
  tags:
    - splunk
    - search_head
    - shsettings
    - comment_macro
  when: splunk_installed_version is version_compare('8.1.0', '<')
