---
# Sets configs for splunk in custom files

- name: "setting configs in file {{ splunk_home }}/etc/{{ splunk_conf_list_items.key }}"
  tags:
    - splunk
    - splunk_conf
  ini_file:
    path: "{{ splunk_home }}/etc/{{ splunk_conf_list_items.key }}"
    section: "{{ item.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: 0600
  become: yes
  become_user: "{{ splunk_user }}"
  notify: restart splunk
  with_items: "{{ splunk_conf_settings_list }}"
  when: splunk_conf_settings_list|length > 0
