---
# This playbook updates the windows hosts file

- name: update hosts entries
  tags:
    - universal_forwarder_windows
    - hosts
  win_hosts:
    state: present
    canonical_name: "{{ item }}"
    ip_address: "{{ hostvars[item].ip_addr }}"
  with_items: "{{ hostvars|list }}"
