---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - splunk_software
  debug:
    msg: "role '{{ role_name }}' start"

- name: Create Splunk Hosts index.html
  tags:
    - splunk
    - splunk_control
  template:
    src: "config/index.html.j2"
    dest: "../config/index.html"