---

- name: find systemd version
  tags:
    - splunk
    - splunk_software
    - splunk_polkit
  shell: "systemctl --version | grep -w systemd | cut -d' ' -f 2"
  check_mode: no
  changed_when: false
  register: systemd_version_output

- name: find polkit version
  tags:
    - splunk
    - splunk_software
    - splunk_polkit
  shell: "pkaction --version | grep -w version | cut -d' ' -f 3"
  check_mode: no
  changed_when: false
  register: polkit_version_output

- name: add splunk polkit rules file
  tags:
    - splunk
    - splunk_software
    - splunk_polkit
  template:
    src: etc/polkit-1/rules.d/10-splunk.rules.j2
    dest: /etc/polkit-1/rules.d/10-{{ splunk_service_name }}.rules
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - systemd_version_output.stdout|int >= 226
    - polkit_version_output.stdout is version_compare('0.105', '>')

- name: add splunk polkit pkla file
  tags:
    - splunk
    - splunk_software
    - splunk_polkit
  template:
    src: etc/polkit-1/localauthority/50-local.d/splunk.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/{{ splunk_service_name }}.pkla
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - systemd_version_output.stdout|int >= 226
    - polkit_version_output.stdout is version_compare('0.105', '<=')

- name: call remove_splunk_sudoers
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_splunk_sudoers.yml
  when: systemd_version_output.stdout|int >= 226

- name: call add_splunk_sudoers
  tags:
    - splunk
    - splunk_software
    - splunk_install
    - splunk_sudoers
  include_tasks: add_splunk_sudoers.yml
  when: systemd_version_output.stdout|int < 226
