---

- name: create splunk backup dir {{ splunk_backup_dir }}
  tags:
    - splunk
    - splunk_software
    - splunk_backup
  file:
    path: "{{ splunk_backup_dir }}"
    state: directory
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0755
  become: yes
  become_user: root

- name: backup splunk etc directory {{ splunk_home }}/etc
  tags:
    - splunk
    - splunk_software
    - splunk_backup
  archive:
    path: "{{ splunk_home }}/etc"
    dest: "{{ splunk_backup_dir }}/{{ splunk_install_app }}_etc_v{{ splunk_installed_version }}_{{ansible_date_time.date|replace('-','')}}_{{ansible_date_time.time|replace(':','')}}.tgz"
    format: gz
  become: yes
  become_user: "{{ splunk_user }}"
