---
# Different checks for installed or target version

- name: checking if splunk is installed
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  stat:
    path: "{{ splunk_home }}/bin/splunk"
  register: splunk_path

- name: splunk is installed here
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  debug:
    msg: 'splunk found as {{ splunk_home }}/bin/splunk'
  when: splunk_path.stat.exists

- name: no Splunk installation found
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  fail:
    msg: "No Splunk installation found, ending"
  when: splunk_path.stat.exists == false

- name: find target version
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: find_target_version.yml
  when: find_target_version|default(true) == true

- name: fail on installed version
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  fail:
    msg: "{{inventory_hostname}} must be upgraded!"
  when:
    - fail_on_missing_upgrade|default(false) == true
    - splunk_installed_version != splunk_target_version

- name: inform about not upgrading
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  debug:
    msg: "Installed version '{{ splunk_installed_version }}' is equal to upgrade version '{{ splunk_target_version }}' -> nothing to upgrade"
  when:
    - inform_on_already_upgraded|default(false) == true 
    - splunk_installed_version == splunk_target_version

- name: set splunk_current_version
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  set_fact:
    splunk_current_version: "{{ splunk_installed_version }}"