---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - splunk_software
  debug:
    msg: "role '{{ role_name }}' start"

- name: "create splunk user and group"
  tags:
    - splunk
    - splunk_software
  include_tasks: users.yml

- name: checking if splunk is installed
  tags:
    - splunk
    - splunk_software
  stat:
    path: "{{ splunk_home }}/bin/splunk"
  register: splunk_path

- name: splunk is installed here
  tags:
    - splunk
    - splunk_software
  debug:
    msg: 'splunk found as {{ splunk_home }}/bin/splunk'
  when: splunk_path.stat.exists

- name: check for existing splunk.secret file
  tags:
    - splunk
    - splunk_software
    - splunk_secret
  stat:
    path: "{{ splunk_auth_dir }}/{{ splunk_install_app }}_splunk.secret"
  become: no
  register: splunk_secret_file
  delegate_to: localhost
  when: splunk_secret_share[splunk_install_app] == true

- name: Fail if no splunk.secret is there and more than one host is deployed
  tags:
    - splunk
    - splunk_software
    - splunk_secret
  fail:
    msg: "Cannot find secret file {{ splunk_auth_dir }}/{{ splunk_install_app }}_splunk.secret. You must first install {{ splunk_install_app }} on one host only."
  when: 
    - splunk_secret_share[splunk_install_app] == true
    - splunk_secret_file.stat.exists == false
    - play_hosts|length > 1

- name: "install the splunk software"
  tags:
    - splunk
    - splunk_software
  include_tasks: install.yml
  when: splunk_path.stat.exists == false

- name: call ulimit_thp
  tags:
    - splunk
    - splunk_software
  include_tasks: ulimit_thp.yml
  when:
    - splunk_install_app == 'splunk'
    - use_systemctl == true
    - use_splunk_systemd|default(false) == false

- name: call add_disable_thp_service
  tags:
    - splunk
    - splunk_software
  include_tasks: add_disable_thp_service.yml
  when:
    - splunk_install_app == 'splunk'
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: call update_splunk_service
  tags:
    - splunk
    - splunk_software
  include_tasks: update_splunk_service.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true
    - splunk_systemd_services[splunk_service_name] is defined

- name: "user interface configuration"
  tags:
    - splunk
    - splunk_software
  include_tasks: ui_config.yml

- name: "host and servername settings"
  tags:
    - splunk
    - splunk_software
  include_tasks: host_servername_config.yml

- name: save shared splunk.secret file
  tags:
    - splunk
    - splunk_software
    - splunk_secret
  synchronize:
    src: "{{ splunk_home }}/etc/auth/splunk.secret"
    dest: "{{ splunk_auth_dir }}/{{ splunk_install_app }}_splunk.secret"
    rsync_path: "{{ become_method|default('sudo') }} -u {{splunk_user}} rsync"
    mode: pull
  become: no
  when:
    - splunk_secret_share[splunk_install_app] == true
    - splunk_secret_file.stat.exists == false

- name: link splunkforwarder to splunk secret file
  tags:
    - splunk
    - splunk_software
    - splunk_secret
  file:
    state: link
    src: "splunk_splunk.secret"
    dest: "{{ splunk_auth_dir }}/splunkforwarder_splunk.secret"
  become: no
  delegate_to: localhost
  when:
    - splunk_secret_share.splunk == true
    - splunk_secret_share.splunkforwarder == true
    - splunk_secret_share.equal == true
    - splunk_secret_file.stat.exists == false
