---
# This playbook removes policy kit config or suoders file

- name: "remove /etc/polkit-1/rules.d/10-{{splunk_service_name}}.rules"
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  file:
    path: "/etc/polkit-1/rules.d/10-{{splunk_service_name}}.rules"
    state: absent

- name: "remove /etc/polkit-1/rules.d/10-Splunkd.rules"
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  file:
    path: "/etc/polkit-1/rules.d/10-Splunkd.rules"
    state: absent
