---

- name: call set_splunk_installed_version from splunk_common
  tags:
    - splunk
    - splunk_software
  include_role:
    name: splunk_common
    tasks_from: set_splunk_installed_version

- name: set splunk systemd-managed to 1
  tags:
    - splunk
    - splunk_software
  set_fact:
    splunk_systemd_managed: "-systemd-managed 1"
  when:
    - use_systemctl == true
    - version_output.stdout is defined
    - splunk_installed_version is version_compare('7.2.2', '>=')

- name: set splunk systemd service file name
  tags:
    - splunk
    - splunk_software
  set_fact:
    splunk_unit_file_name: "-systemd-unit-file-name {{splunk_service_name}}"
  when:
    - use_systemctl == true
    - version_output.stdout is defined
    - splunk_installed_version is version_compare('7.2.2', '>=')

- name: set splunk create-polkit-rules to 1
  tags:
    - splunk
    - splunk_software
  set_fact:
    splunk_create_polkit_rules: "-create-polkit-rules 1"
  when:
    - use_policykit == true
    - use_systemctl == true
    - version_output.stdout is defined
    - splunk_installed_version is version_compare('8.1.1', '>=')
