---
# This playbook uninstalls splunk enterprise or splunk universal forwarder

- name: check for splunk binary
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  stat:
    path: "{{ splunk_home }}/bin/splunk"
  register: check_splunk_binary_file

- name: check for splunk systemd unit file {{splunk_service_name}}.service
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  stat:
    path: "/etc/systemd/system/{{splunk_service_name}}.service"
  register: check_systemd_unit_file
  when: 
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: stop and disable {{splunk_service_name}} service
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  service:
    name: "{{splunk_service_name}}.service"
    state: stopped
    enabled: no
  when: 
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true
    - check_systemd_unit_file.stat.exists == true

- name: check for thp service file
  stat:
    path: "/etc/systemd/system/disable-thp.service"
  register: check_thp_systemd

- name: call remove_disable_thp_service
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  include_tasks: remove_disable_thp_service.yml
  when:
    - use_systemctl == true
    - check_thp_systemd.stat.exists == true

- name: check if splunk is stopped
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  shell: "pgrep splunkd"
  register: grep_result
  check_mode: no
  failed_when: "grep_result.rc > 1"
  changed_when: "grep_result.rc == 0"

- name: kill splunk processes
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  shell: "pkill -9 -u splunk"
  # become: yes
  # become_user: "{{ splunk_user }}"
  when: grep_result.rc == 0

- name: call disable_boot-start
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  include_tasks: disable_boot-start.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true
    - check_systemd_unit_file.stat.exists == true
    - check_splunk_binary_file.stat.exists == true

- name: remove init.d scripts
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
    - splunk_remove_init
  include_tasks: remove_init_and_ulimit.yml

- name: make sure files are gone
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/{{splunk_service_name}}.service"
    - /etc/systemd/system/disable-thp.service
    - /etc/init.d/splunk

- name: call remove_custom_policykit
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  include_tasks: remove_custom_policykit.yml

- name: call remove_splunk_sudoers
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_splunk_sudoers.yml

# Find all directories to remove, except lost+found
- name: find files to remove all under {{splunk_home}}/
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  find:
    paths: "{{splunk_home}}/"
    file_type: any
    recurse: no
    patterns: '.*(?<!lost\+found)$'
    use_regex: yes
  register: files_to_delete

# Remove as user splunk to prevent removing mounted directories
- name: remove all under {{splunk_home}}/
  tags:
    - splunk
    - splunk_software
    - splunk_uninstall
  file:
    path: "{{item.path}}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  become: yes
  become_user: "{{ splunk_user }}"

# Do not remove this directory, since a mounted filesystem could be inside
#  tags:
#    - splunk
#    - splunk_software
#    - splunk_uninstall
#- name: "remove {{ splunk_home }}"
#  file:
#    path: "{{ splunk_home }}"
#    state: absent
