---

- name: "update {{splunk_service_name}} systemd service file"
  tags:
    - splunk
    - splunk_software
    - splunk_unit_file
  ini_file:
    path: "/etc/systemd/system/{{splunk_service_name}}.service"
    section: "{{ item.section }}"
    option: "{{ item.var }}"
    value: "{{ item.val }}"
    owner: root
    group: root
    mode: 0700
    no_extra_spaces: yes
  with_items: "{{ splunk_systemd_services_updates }}"
  when: use_systemctl == true and splunk_systemd_services[splunk_service_name] is defined

- name: commit changes to systemctl
  tags:
    - splunk
    - splunk_software
    - splunk_unit_file
  command: systemctl daemon-reload
  when: use_systemctl == true
