---
# playbook fot upgrading splunk

- name: display upgrade version info
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  debug:
    msg: "Upgrade {{ splunk_install_app }} from version '{{ splunk_current_version }}' to version '{{ splunk_target_version }}'"

- name: backup splunk etc
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: backup_splunk_etc.yml

- name: stop splunk by service control
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: stop_splunk.yml

- name: check /etc/init.d/splunk
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  stat:
    path: "/etc/init.d/splunk"
  register: check_splunk_init

- name: set boot_start_migration variable
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  set_fact:
    boot_start_migration: true
  when:
    - check_splunk_init.stat.exists == true
    - splunk_target_version is version_compare('7.2.2', '>=')

- name: remove init.d, ulimit settings and THP scripts
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_init_and_ulimit.yml
  when: boot_start_migration|default(false) == true

- name: call disable_boot-start
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: disable_boot-start.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: call remove_custom_policykit
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_custom_policykit.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: call remove_splunk_sudoers
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_splunk_sudoers.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: call remove_disable_thp_service
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: remove_disable_thp_service.yml
  when:
    - splunk_install_app == 'splunk'
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: upload and extract the splunk software
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: upload_and_extract.yml
  when: splunk_path.stat.exists == true

- name: set enable boot-start args
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: set_enable_boot_start_args.yml

- name: call enable_boot-start
  tags:
    - splunk
    - splunk_software
    - splunk_install
  include_tasks: enable_boot-start.yml
  when: boot_start_migration|default(false) == true or use_systemctl == true and use_splunk_systemd|default(false) == true

- name: call check_systemd_file from splunk_common
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_role:
    name: splunk_common
    tasks_from: check_systemd_file

- name: call update_splunk_service
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: update_splunk_service.yml
  when:
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true
    - splunk_systemd_services[splunk_service_name] is defined

- name: call add_disable_thp_service
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_disable_thp
  include_tasks: add_disable_thp_service.yml
  when:
    - splunk_install_app == 'splunk'
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: call add_custom_policykit
  tags:
    - splunk
    - splunk_software
    - splunk_install
    - splunk_polkit
  include_tasks: add_custom_policykit.yml
  when: 
    - use_policykit == true
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true
    - splunk_create_polkit_rules is not defined

- name: call add_splunk_sudoers
  tags:
    - splunk
    - splunk_software
    - splunk_install
    - splunk_sudoers
  include_tasks: add_splunk_sudoers.yml
  when: 
    - use_policykit == false
    - use_systemctl == true
    - use_splunk_systemd|default(false) == true

- name: start splunk by service control
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: start_splunk.yml
