---
# playbook for upgrading splunk

- name: call check_splunk_version
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: check_splunk_version.yml
  vars:
    inform_on_already_upgraded: true

- name: call upgrade
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
  include_tasks: upgrade.yml
  when: splunk_installed_version != splunk_target_version