---

- name: check cluster state
  tags:
    - splunk
    - splunk_software
    - splunk_rest
    - splunk_upgrade
    - splunk_upgrade_idxc_rolling
  include_tasks: splunk_rest.yml
  vars:
    splunk_rest_endpoint: /services/cluster/master/status

- name: set state variables
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_idxc_rolling
  set_fact:
    idxc_searchable_rolling: "{{ splunk_rest_json_output.entry[0].content.searchable_rolling|bool }}"
    idxc_service_ready_flag: "{{ splunk_rest_json_output.entry[0].content.service_ready_flag|bool }}"
  vars:
    splunk_rest_json_output: "{{ splunk_rest_output.content|to_json|from_json }}"

- name: finalize rolling upgrade
  tags:
    - splunk
    - splunk_software
    - splunk_rest
    - splunk_upgrade
    - splunk_upgrade_idxc_rolling
  include_tasks: splunk_rest.yml
  vars:
    splunk_rest_endpoint: /services/cluster/master/control/control/rolling_upgrade_finalize
    http_method: POST
  when: idxc_searchable_rolling == true

- name: finalize output
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_idxc_rolling
  debug:
    msg: "{{ splunk_rest_json_output.messages[0].text }}"
  when: idxc_searchable_rolling == true
  changed_when: idxc_searchable_rolling == true

- name: finalize output
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_idxc_rolling
  debug:
    msg: "Cluster searchable rolling was already finalized."
  when: idxc_searchable_rolling == false