---

- name: check cluster state
  tags:
    - splunk
    - splunk_software
    - splunk_rest
    - splunk_upgrade
    - splunk_upgrade_shc_rolling
  include_tasks: splunk_rest.yml
  vars:
    splunk_rest_endpoint: /services/shcluster/status?advanced=1
  when: inventory_hostname == splunk_shc_host_list|first

- name: set state variables
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_shc_rolling
  set_fact:
    shc_rolling_restart_flag: "{{ splunk_rest_json_output.entry[0].content.captain.rolling_restart_flag|bool }}"
    shc_rolling_upgrade_flag: "{{ splunk_rest_json_output.entry[0].content.captain.rolling_upgrade_flag|bool }}"
    shc_service_ready_flag: "{{ splunk_rest_json_output.entry[0].content.captain.service_ready_flag|bool }}"
  vars:
    splunk_rest_json_output: "{{ splunk_rest_output.content|to_json|from_json }}"
  when: inventory_hostname == splunk_shc_host_list|first

- name: finalize rolling upgrade
  tags:
    - splunk
    - splunk_software
    - splunk_rest
    - splunk_upgrade
    - splunk_upgrade_shc_rolling
  include_tasks: splunk_rest.yml
  vars:
    splunk_rest_endpoint: /services/shcluster/captain/control/control/upgrade-finalize
    http_method: POST
  when:
    - inventory_hostname == splunk_shc_host_list|first 
    - shc_rolling_upgrade_flag == true

- name: finalize output
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_shc_rolling
  debug:
    msg: "{{ splunk_rest_json_output.messages[0].text }}"
  when:
    - inventory_hostname == splunk_shc_host_list|first 
    - shc_rolling_upgrade_flag == true
  changed_when: shc_rolling_upgrade_flag == true

- name: finalize output
  tags:
    - splunk
    - splunk_software
    - splunk_upgrade
    - splunk_upgrade_shc_rolling
  debug:
    msg: "Cluster searchable rolling was already finalized."
  when:
    - inventory_hostname == splunk_shc_host_list|first 
    - shc_rolling_upgrade_flag == false