---

- name: upload and unarchive splunk archive from ansible host
  tags:
    - splunk
    - splunk_software
  unarchive:
    src: "{{splunk_archive.0}}"
    dest: "{{ splunk_install_dir }}/"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    extra_opts:
      - "--dereference"
  when: splunk_download is not defined or
        (splunk_install_app == "splunk" and splunk_download.splunk|default(false) == false) or
        (splunk_install_app == "splunkforwarder" and splunk_download.splunkforwarder|default(false) == false)

- name: define splunk archive download url
  tags:
    - splunk
    - splunk_software
  set_fact:
    splunk_url: 'https://d7wz6hmoaavd0.cloudfront.net/products/{%- if splunk_install_app == "splunk" -%}splunk{%- else -%}universalforwarder{%- endif -%}/releases/{{splunk_target_version}}/linux/{{splunk_archive.0|basename}}'
  when: splunk_download is defined and
        (splunk_install_app == "splunk" and splunk_download.splunk|default(false) == true or
        splunk_install_app == "splunkforwarder" and splunk_download.splunkforwarder|default(false) == true)

- name: download the splunk archive from splunk.com
  tags:
    - splunk
    - splunk_software
  get_url:
    url: "{{ splunk_url }}"
    dest: "/tmp/splunk.tar.gz"
    timeout: 60
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    force: yes
  when: splunk_download is defined and
        (splunk_install_app == "splunk" and splunk_download.splunk|default(false) == true or
        splunk_install_app == "splunkforwarder" and splunk_download.splunkforwarder|default(false) == true)

- name: extract splunk archive
  tags:
    - splunk
    - splunk_software
  unarchive:
    src: "/tmp/splunk.tar.gz"
    dest: "{{ splunk_install_dir }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    remote_src: yes
    extra_opts:
      - "--dereference"
  when: splunk_download is defined and
        (splunk_install_app == "splunk" and splunk_download.splunk|default(false) == true or
        splunk_install_app == "splunkforwarder" and splunk_download.splunkforwarder|default(false) == true)

# This is needed when having splunk_home linked to another directory
- name: set owner {{ splunk_user }}:{{ splunk_group }} for {{ splunk_home }}
  tags:
    - splunk
    - splunk_software
  file:
    path: "{{ splunk_home }}/."
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0755'

- name: remove splunk install archive
  tags:
    - splunk
    - splunk_software
  file:
    path: "/tmp/splunk.tar.gz"
    state: absent
  when: splunk_download is defined and
        (splunk_install_app == "splunk" and splunk_download.splunk|default(false) == true or
        splunk_install_app == "splunkforwarder" and splunk_download.splunkforwarder|default(false) == true)
