---
# get the list of existing dservers and add the missing ones

- name: get list of current distributedSearch servers
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  # Same command is in search_head/tasks/search_peers.yml
  include_role:
    name: splunk_software
    tasks_from: splunk_rest
  vars:
    splunk_rest_endpoint: /services/search/distributed/peers

- name: create current_dservers list
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
    - splunk_rest
  set_fact:
    current_dservers: "{{ splunk_rest_json_output | json_query(jmesquery) | map('regex_replace', ':\\d+$', '') }}"
  vars:
    jmesquery: "entry[*].name"

- name: call add_dserver
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  include_tasks: add_dserver.yml
  with_items:
    - "{{ splunk_dservers | difference(current_dservers) }}"
  loop_control:
    loop_var: dserver_name
  when: "splunk_dservers|difference(current_dservers)|length > 0"
