---
# This playbook install a hosts file for all the hosts

#TODO Remove in future versions
- name: remove vagrant-hostmanager entries
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    state: absent
    marker: "## {mark}"
    marker_begin: "vagrant-hostmanager-start"
    marker_end: "vagrant-hostmanager-end"
  become: yes
  become_user: root

- name: add splunk hosts to /etc/hosts
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ splunk_hosts_entries }}
    marker: "# {mark} SPLUNKENIZER MANAGED BLOCK (splunk hosts)"
  become: yes
  become_user: root
