---
# Main playbook for this role

- name:
  include_tasks: set_hostname.yml
  when: ansible_os_family|lower != 'windows'

- name:
  include_tasks: packages.yml
  when:
    - packages|default([],true)|length > 0
    - ansible_os_family|lower != 'windows'

- name:
  include_tasks: check_ansible_requirements.yml
  when: ansible_os_family|lower != 'windows'

- name:
  include_tasks: users.yml
  when: ansible_os_family|lower != 'windows'

- name:
  include_tasks: time.yml
  when: ansible_os_family|lower != 'windows'

- name:
  include_tasks: disable_selinux.yml
  when:
    - disable_selinux|default(false) == true
    - ansible_os_family|lower != 'windows'
    - "'role_universal_forwarder' not in group_names"

- name:
  include_tasks: disable_apparmor.yml
  when:
    - ansible_os_family|lower != 'windows'
    - disable_apparmor|default(false) == true

- name:
  include_tasks: hosts.yml
  when:
    - ansible_os_family|lower != 'windows'
    - update_hosts_file|default(false) == true

- name:
  include_tasks: fix_time_sync.yml
  when:
    - ansible_os_family|lower != 'windows'
    - enable_time_sync_cron|default(false) == true
