---
# This playbook installs additional os packages

- name: Run apt-get update
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install additional os packages
  tags:
    - common
    - packages
  package:
    name: "{{ packages }}" 
    state: latest
