---
# This playbook install a basic user with the login keys

- name: Adding splunk aliases
  tags:
    - common
    - bashrc
  copy:
    src: home/ansible_user/bashrc.splunk
    dest: "~{{ ansible_user }}/.bashrc.splunk"
    mode: 0644
  become: yes
  become_user: "{{ ansible_user }}"

- name: insert/update bashrc for splunk stuff
  tags:
    - common
    - bashrc
  blockinfile:
    create: yes
    path: "~{{ ansible_user }}/.bashrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "export PATH"
    content: |
      if [ -f ~/.bashrc.splunk ]; then
        . ~/.bashrc.splunk
      fi
