---
# Check if we can access the storage layer for storing buckets

- name: "getting volume status"
  tags:
    - splunk
    - indexer
    - check_volume_path
  stat:
    path: "{{ volume_path }}"
  register: volumepath

- name: "check if volume exists"
  tags:
    - splunk
    - indexer
    - check_volume_path
  fail:
    msg: "volume:{{ volume_name }} path: {{ volume_path }} does not exist"
  when: volumepath.stat.exists == false

- name: "check if volume path is a directory"
  tags:
    - splunk
    - indexer
    - check_volume_path
  fail:
    msg: "volume:{{ volume_name }} path: {{ volume_path }} is not a directory"
  when: volumepath.stat.isdir == false

- name: "check if volume path is own by splunk user"
  tags:
    - splunk
    - indexer
    - check_volume_path
  fail:
    msg: "volume:{{ volume_name }} path: {{ volume_path }} is not owned by user {{splunk_user}}"
  when: volumepath.stat.pw_name != splunk_user

- name: "check if volume path is writeable"
  tags:
    - splunk
    - indexer
    - check_volume_path
  fail:
    msg: "volume:{{ volume_name }} path: {{ volume_path }} is not writable by user {{splunk_user}}"
  when: volumepath.stat.wusr == false
