---
# Main playbook for this role

- name: start indexer cluster node
  tags:
    - splunk
    - indexer
    - idxcluster
  debug:
    msg: "Configuring indexer cluster"

- name: apply baseconfig app org_cluster_indexer_base
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxcluster
    - org_cluster_indexer_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_cluster_indexer_base'
    app_path: '{{splunk_home}}/etc/apps'

- name: apply baseconfig app org_site_n_indexer_base
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxcluster
    - org_site_n_indexer_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_site_n_indexer_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: site is defined and "'site' in site"
