---
# Main playbook for this role

- name: start indexer cluster node
  tags:
    - splunk
    - indexer
    - idxsingle
  debug:
    msg: "Configuring single indexer"

- name: apply baseconfig app org_all_deploymentclient
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_all_deploymentclient
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_deploymentclient'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length > 0 and inventory_hostname not in groups.role_deployment_server

- name: apply baseconfig app org_full_license_server
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_full_license_server
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_full_license_server'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 and splunk_license_manager|default()|length > 0 and inventory_hostname not in groups.role_license_manager|default([])

- name: apply baseconfig app org_all_indexer_base
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_all_indexer_base
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexer_base'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 or inventory_hostname in groups.role_deployment_server

- name: apply baseconfig app org_indexer_volume_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_indexer_volume_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_indexer_volume_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 or inventory_hostname in groups.role_deployment_server

- name: apply baseconfig app org_all_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_all_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_all_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  when: splunk_deployment_server|default()|length == 0 or inventory_hostname in groups.role_deployment_server

- name: apply baseconfig app org_s2_indexer_indexes
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - org_s2_indexer_indexes
  include_role:
    name: baseconfig_app
  vars:
    app_name: 'org_s2_indexer_indexes'
    app_path: '{{splunk_home}}/etc/apps'
  when: 
    - splunk_volume_defaults.remotePath is defined
    - splunk_deployment_server|default()|length == 0 or inventory_hostname in groups.role_deployment_server

- name: call update_dserver from role monitoring_console
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - monitoring_console
    - dserver
  include_role:
    name: monitoring_console
    tasks_from: update_dserver
  vars:
    splunk_dservers: "[ '{{ inventory_hostname }}' ]"
  when: splunk_monitoring_console|default()|length > 0 and inventory_hostname not in groups.role_monitoring_console

- name: add as search peer on search head
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - search_head
    - dserver
  include_role:
    name: search_head
    tasks_from: loop_search_heads
  when: inventory_hostname not in groups.role_search_head
