---
# Main playbook for this role

- name: start role tasks
  tags:
    - splunk
    - indexer
  debug:
    msg: "role '{{ role_name }}' start"

#TODO: create volume directories
#- name: create volume directories
#  tags:
#    - splunk
#    - indexer
#    - create_volume_path
#  file:
#    path: "{{ item.value.path }}"
#    state: directory
#    owner: "{{splunk_user}}"
#    group: "{{splunk_group}}"
#    mode: 0755
#  with_dict: "{{ splunk_indexer_volumes }}"
#  when: splunk_indexer_volumes_local|length > 0

- name: check volume pathes
  tags:
    - splunk
    - indexer
    - check_volume_path
  include_tasks: check_volume_path.yml
  with_dict: "{{ splunk_indexer_volumes_local }}"
  vars:
    volume_name: "{{ item.key }}"
    volume_path: "{{ item.value.path|default(splunk_home+'/var/lib/splunk') }}"
  when: splunk_indexer_volumes_local|length > 0

- name: install certs for inputs ssl
  tags:
    - splunk
    - splunk_baseconfig
    - indexer
    - idxsingle
    - idxcluster
    - inputs_ssl
  include_role:
    name: baseconfig_app
    tasks_from: splunk_ssl_inputs_certs
  when: splunk_ssl.inputs.enable == true and splunk_ssl.inputs.own_certs == true

- include_tasks: idxcluster.yml
  when: idxc_name is defined

- include_tasks: idxsingle.yml
  when: idxc_name is not defined
