---

- name: disable splunkweb
  hosts: all,!role_universal_forwarder,!role_universal_forwarder_windows
  become: yes
  become_user: root

  tasks:

    - name: call disable_splunkwebfrom role splunk_common
      include_role:
        name: splunk_software
        tasks_from: disable_splunkweb.yml
