---

# Usage: run_splunk_command.yml --limit <hostname> -e "splunk_command='show shcluster-status'"

- name: run Splunk command
  hosts: role_cluster_manager,role_deployer,role_deployment_server,role_heavy_forwarder,role_indexer,role_license_manager,role_monitoring_console,role_search_head,role_universal_forwarder
  become: yes
  become_user: root

  tasks:

    - name: call splunk_command from role splunk_common
      include_role:
        name: splunk_software
        tasks_from: splunk_command
