---
# This playbook add/updates splunk config file settings

- name: run splunk_conf role
  hosts: all:!role_universal_forwarder_windows
  become: yes
  become_user: root

  tasks:
    - name: call splunk_conf role
      include_role:
        name: splunk_conf
      when:
        - splunk_conf is defined
        - splunk_conf is mapping