---

- name: start splunk
  hosts: role_cluster_manager,role_deployer,role_deployment_server,role_heavy_forwarder,role_indexer,role_license_manager,role_monitoring_console,role_search_head,role_universal_forwarder
  become: yes
  become_user: root

  tasks:

    - name: call start splunk from role splunk_common
      include_role:
        name: splunk_software
        tasks_from: start_splunk
