---
# This playbook install the base config app

- name: "call replace_master_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  include_tasks: replace_master_uri.yml
  vars:
    splunk_file_to_change: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"

- name: "({{ app_name }}) setting mode"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: mode
    value: "{{splunk_cluster_peer_mode}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting clustering manager_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: "{{splunk_manager_uri_var}}"
    value: "https://{{splunk_idxc_cm}}:8089"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting unhashed pass4SymmKey"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: pass4SymmKey
    value: "{{splunk_idxc_pass}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: app_local.stat.exists == false

- name: "({{ app_name }}) setting replication port"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    regexp: '(<PORT_NUM>)'
    replace: '{{splunk_idxc_replication_port}}'
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) disable none-ssl in inputs.conf"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
    - inputs_ssl
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/inputs.conf"
    section: "splunktcp://{{inputs_port}}"
    option: "disabled"
    value: "1"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: splunk_ssl.inputs.enable == true

- name: "({{ app_name }}) enable ssl in inputs.conf"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
    - inputs_ssl
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/inputs.conf"
    section: "splunktcp-ssl://{{inputs_port_ssl}}"
    option: "disabled"
    value: "0"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: splunk_ssl.inputs.enable == true

- name: "({{ app_name }}) setting ssl configs in inputs.conf"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
    - inputs_ssl
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/inputs.conf"
    section: "SSL"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  with_dict: "{{ splunk_ssl.inputs.config }}"
  when: splunk_ssl.inputs.enable == true

- name: "({{ app_name }}) call set_bucket_tunings"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_indexer_base
  include_tasks: set_bucket_tunings.yml