---
# This playbook install the base config app

- name: "({{ app_name }}) setting indexer site"
  tags:
    - splunk
    - splunk_baseconfig
    - org_site_n_indexer_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: general
    option: site
    value: "{{site}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
