---
# This playbook install the base config app

- name: Fail if homePath != coldPath (SmartStore)
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  fail:
    msg: "homePath ({{splunk_volume_defaults.homePath|default('primary')}}) must be equal to coldPath ({{splunk_volume_defaults.coldPath|default('primary')}}) when using SmartStore"
  when: 
    - splunk_volume_defaults.remotePath is defined
    - splunk_volume_defaults.homePath|default("primary") != splunk_volume_defaults.coldPath|default("primary")

- name: "({{ app_name }}) set index default path options"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  include_tasks: set_index_vars.yml
  with_dict: "{{ splunk_indexes_path_settings|default({}) }}"
  vars:
    index_name: "{{ item.key }}"
    index_vars: "{{ item.value }}"
    splunk_indexes: { 'default': {} }
  when:
    - splunk_indexes_default_paths|default(false) == true
    - splunk_indexes_path_settings|default({})|length > 0

- name: "({{ app_name }}) set index path options"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  include_tasks: set_index_vars.yml
  with_dict: "{{ splunk_indexes_path_settings|default({}) }}"
  vars:
    index_name: "{{ item.key }}"
    index_vars: "{{ item.value }}"
  when:
    - splunk_indexes_default_paths|default(false) == false 
    - splunk_indexes_path_settings|default({})|length > 0

- name: "({{ app_name }}) set index options"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  include_tasks: set_index_vars.yml
  with_dict: "{{ splunk_indexes_settings|default({}) }}"
  vars:
    index_name: "{{ item.key }}"
    index_vars: "{{ item.value }}"

  when: splunk_indexes_settings|default({})|length > 0

- name: "({{ app_name }}) configure volume for homePath"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    regexp: '^(homePath\s*=\s*)volume:\w*'
    replace: '\1volume:{{splunk_volume_defaults.homePath|default("primary")}}'
  notify: restart splunk

- name: "({{ app_name }}) configure volume for coldPath"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    regexp: '^(coldPath\s*=\s*)volume:\w*'
    replace: '\1volume:{{splunk_volume_defaults.coldPath|default("primary")}}'
  notify: restart splunk
