---
# This playbook install the base config app

- name: "call replace_master_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_full_license_server
  include_tasks: replace_master_uri.yml
  vars:
    splunk_file_to_change: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"

- name: "({{ app_name }}) setting license manager_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_full_license_server
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: license
    option: "{{splunk_manager_uri_var}}"
    value: "https://{{splunk_license_manager|first}}:8089"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
