---
# This playbook install the base config app

- name: "call replace_master_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  include_tasks: replace_master_uri.yml
  vars:
    splunk_file_to_change: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"

- name: "({{ app_name }}) setting defaultGroup value"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout
    option: defaultGroup
    value: "{{ splunk_outputs_tcpout_list|map('regex_replace','^(.*)$','\\1_indexers')|join(',') }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  when: splunk_outputs_idxc_list|length > 0 or splunk_outputs_idx_list|length > 0

- name: "({{ app_name }}) rename tcpout:primary_indexers if clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    regexp: '\[tcpout:primary_indexers\]'
    replace: "[tcpout:{{ splunk_outputs_idxc_list|first+'_indexers' }}]"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  when: splunk_outputs_idxc_list|length > 0

- name: set input port
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  set_fact:
    idx_port: "{{ inputs_port }}"
  when: splunk_ssl.outputs.enable != true

- name: set ssl input port
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  set_fact:
    idx_port: "{{ inputs_port_ssl }}"
  when: splunk_ssl.outputs.enable == true

- name: install certs for outputs ssl
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
    - outputs_ssl
  include_role:
    name: baseconfig_app
    tasks_from: splunk_ssl_outputs_certs
  when: splunk_ssl.outputs.enable == true and splunk_ssl.outputs.own_certs == true

- name: "({{ app_name }}) setting server in tcpout stanza for clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:{{ item.key+'_indexers' }}
    option: server
    value: "{% set comma = joiner(',') %}{% for idx in item.value %}{{ comma() }}{{ idx }}:{{idx_port}}{% endfor %}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  with_dict: "{{ splunk_outputs_idxc_list }}"
  when: splunk_outputs_idxc_list|length > 0

- name: "({{ app_name }}) setting indexerDiscovery for indexer clusters"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:{{ item.idxc_name+'_indexers' }}
    option: indexerDiscovery
    value: "{{ item.idxc_name+'_indexers' }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  with_items: "{{ splunk_outputs_discovery_idxc_list }}"
  when: splunk_outputs_discovery_idxc_list|length > 0

- name: "({{ app_name }}) setting indexer discovery password"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: indexer_discovery:{{ item.idxc_name+'_indexers' }}
    option: pass4SymmKey
    value: "{{ item.password }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  with_items: "{{ splunk_outputs_discovery_idxc_list }}"
  when: splunk_outputs_discovery_idxc_list|length > 0

- name: "({{ app_name }}) setting indexer discovery manager_uri"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: indexer_discovery:{{ item.idxc_name+'_indexers' }}
    option: "{{splunk_manager_uri_var}}"
    value: "https://{{item.master }}:8089"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  with_items: "{{ splunk_outputs_discovery_idxc_list }}"
  when: splunk_outputs_discovery_idxc_list|length > 0

- name: "({{ app_name }}) setting ssl in tcpout stanza for clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - outputs_ssl
    - org_all_forwarder_outputs
  include_role:
    name: baseconfig_app
    tasks_from: org_all_forwarder_outputs_idxc_ssl
  with_items: "{{ splunk_outputs_idxc_list }}"
  loop_control:
    loop_var: index_cluster_name
  when: splunk_outputs_idxc_list|length > 0 and splunk_ssl.outputs.enable == true

- name: "({{ app_name }}) rename tcpout:primary_indexers if non clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    regexp: '\[tcpout:primary_indexers\]'
    replace: "[tcpout:all_indexers]"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  when: splunk_outputs_idxc_list|length == 0 and splunk_outputs_idx_list|length > 0

- name: "({{ app_name }}) setting server in tcpout stanza for non clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:all_indexers
    option: server
    value: "{% set comma = joiner(',') %}{% for idx in splunk_outputs_idx_list %}{{ comma() }}{{ idx }}:{{idx_port}}{% endfor %}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0644
  notify: restart splunk
  when: splunk_outputs_idx_list|length > 0

- name: "({{ app_name }}) setting other ssl configs in tcpout stanza for non clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
    - outputs_ssl
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:all_indexers
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  with_dict: "{{ splunk_ssl.outputs.config }}"
  when:
    - splunk_outputs_idx_list|length > 0
    - splunk_ssl.outputs.enable == true

- name: "({{ app_name }}) setting ssl certfile configs in tcpout stanza for non clustered indexers"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_forwarder_outputs
    - outputs_ssl
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/outputs.conf"
    section: tcpout:all_indexers
    option: "{{ item.varkey }}"
    value: "$SPLUNK_HOME/etc/apps/{{ app_dest_name }}/default/{{ item.varvalue|basename }}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  with_items:
    - { varkey: "sslRootCAPath", varvalue: "{{ splunk_ssl.outputs.config.sslRootCAPath|default('cacert.pem') }}" }
    - { varkey: "sslCertPath", varvalue: "{{ splunk_ssl.outputs.config.sslCertPath|default('client.pem') }}" }
  when:
    - splunk_outputs_idx_list|length
    - splunk_ssl.outputs.enable == true
    - splunk_ssl.outputs.own_certs == true
