---
# This playbook install the base config app

- name: "({{ app_name }}) setting mode"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: mode
    value: "{{splunk_cluster_manager_mode}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting replication factor"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: replication_factor
    value: "{{splunk_idxc_rf}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting search factor"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: search_factor
    value: "{{splunk_idxc_sf}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting cluster label"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: cluster_label
    value: "{{splunk_idxc_label}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk

- name: "({{ app_name }}) setting unhashed clustering pass4SymmKey"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: pass4SymmKey
    value: "{{splunk_idxc_pass}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: app_local.stat.exists == false

- name: "({{ app_name }}) setting unhashed indexer discovery pass4SymmKey"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: indexer_discovery
    option: pass4SymmKey
    value: "{{idxc_discovery_password}}"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: app_local.stat.exists == false and idxc_discovery_password is defined

- name: "({{ app_name }}) setting summary_replication = true"
  tags:
    - splunk
    - splunk_baseconfig
    - org_cluster_manager_base
  ini_file:
    path: "{{ app_path }}/{{ app_dest_name }}/local/server.conf"
    section: clustering
    option: summary_replication
    value: "true"
    owner: "{{splunk_user}}"
    group: "{{splunk_group}}"
    mode: 0600
  notify: restart splunk
  when: splunk_installed_version is version_compare('6.4.0', '>=') and splunk_volume_defaults.remotePath is not defined